sudo: required 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - avishaya@amazon.com
env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="kinetic" PRERELEASE=true
    - ROS_DISTRO="melodic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="melodic" PRERELEASE=true
install:
  - git clone -b build-tool-depend https://github.com/AAlon/utils-common.git utils-common
  - git clone https://github.com/aws-robotics/utils-ros1.git utils-ros1
  - git clone https://github.com/aws-robotics/cloudwatchlogs-ros1 cloudwatchlogs-ros1
  - git clone https://github.com/aws-robotics/cloudwatch-common cloudwatch-common
  - git clone https://github.com/aws-robotics/cloudwatchmetrics-ros1 cloudwatchmetrics-ros1
  - git clone https://github.com/aws-robotics/health-metrics-collector-ros1 health-metrics-collector-ros1
  - git clone https://github.com/aws-robotics/monitoringmessages-ros1 monitoringmessages-ros1
  - git clone https://github.com/ros-industrial/industrial_ci.git .ros_ci
script:
  - .ros_ci/travis.sh
