sudo: required 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - avishaya@amazon.com
env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="kinetic" PRERELEASE=true
    - ROS_DISTRO="lunar"   PRERELEASE=true
    - ROS_DISTRO="lunar"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="melodic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="melodic" PRERELEASE=true
install:
  - git clone https://github.com/aws-robotics/utils-common.git utils-common
  - git clone https://github.com/aws-robotics/utils-ros1.git utils-ros1
  - git clone https://github.com/ros-industrial/industrial_ci.git .ros_ci
script:
  - .ros_ci/travis.sh
