sudo: required 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - avishaya@amazon.com
env:
  global:
    - GITHUB_ACCOUNT=aws-robotics
    # uncomment PACKAGE_NAMES to build unit tests - REQUIRED if you'd like to run unit tests using colcon
    - PACKAGE_NAMES=aws_common
  matrix:
    # define DOWNSTREAM_GITHUB_REPO=name-of-your-repo if you'd like to trigger downstream repos' travis builds
    - ROS_DISTRO=kinetic ROS_VERSION=1
    - ROS_DISTRO=melodic ROS_VERSION=1
    - ROS_DISTRO=dashing ROS_VERSION=2
install:
  - git clone https://github.com/aws-robotics/utils-common.git utils-common
  - git clone https://github.com/AAlon/travis-scripts .ros_ci
script:
  - .ros_ci/ce_build.sh
