sudo: required 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - avishaya@amazon.com
env:
  global:
    - GITHUB_ACCOUNT=aws-robotics
    # uncomment PACKAGE_NAMES to build unit tests - REQUIRED if you'd like to run unit tests using colcon
    - PACKAGE_NAME=h264_encoder_core
  matrix:
    # define DOWNSTREAM_GITHUB_REPO=name-of-your-repo if you'd like to trigger downstream repos' travis builds
    - ROS_DISTRO=kinetic ROS_VERSION=1 BRANCH=master
    - ROS_DISTRO=melodic ROS_VERSION=1 BRANCH=master
    - ROS_DISTRO=dashing ROS_VERSION=2 BRANCH=master
    - ROS_DISTRO=kinetic ROS_VERSION=1 BRANCH=release-v2
    - ROS_DISTRO=melodic ROS_VERSION=1 BRANCH=release-v2
    - ROS_DISTRO=dashing ROS_VERSION=2 BRANCH=release-v2
install:
  - git clone -b ${BRANCH} https://github.com/aws-robotics/kinesisvideo-encoder-common.git kinesisvideo-encoder-common
  - git clone https://github.com/aws-robotics/travis-scripts .ros_ci
  - cd .ros_ci && git checkout a117647b5f9e871047b357131bc9b5399a89a839 && cd ..
script:
  - .ros_ci/ce_build.sh
