sudo: required 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - avishaya@amazon.com
env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="kinetic" PRERELEASE=true
    - ROS_DISTRO="melodic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="melodic" PRERELEASE=true
install:
  - git clone https://github.com/aws-robotics/utils-common.git utils-common
  - git clone https://github.com/aws-robotics/utils-ros1.git utils-ros1
  - git clone https://github.com/aws-robotics/cloudwatch-common cloudwatch-common
  - git clone https://github.com/aws-robotics/cloudwatchlogs-ros1 cloudwatchlogs-ros1
  - git clone https://github.com/aws-robotics/cloudwatchmetrics-ros1 cloudwatchmetrics-ros1
  - git clone https://github.com/aws-robotics/health-metrics-collector-ros1 health-metrics-collector-ros1
  - git clone https://github.com/aws-robotics/kinesisvideo-common kinesisvideo-common
  - cd kinesisvideo-common && git checkout fe30a688bc7a71ea1e4dcae5d3521cec1b51c6cb && cd ..
  - git clone https://github.com/aws-robotics/kinesisvideo-ros1 kinesisvideo-ros1
  - git clone https://github.com/aws-robotics/kinesisvideo-encoder-common kinesisvideo-encoder-common
  - git clone https://github.com/aws-robotics/kinesisvideo-encoder-ros1 kinesisvideo-encoder-ros1
  - git clone https://github.com/aws-robotics/monitoringmessages-ros1 monitoringmessages-ros1
  - git clone https://github.com/aws-robotics/lex-ros1 lex-ros1
  - git clone https://github.com/aws-robotics/tts-ros1 tts-ros1
  - git clone https://github.com/ros-industrial/industrial_ci.git .ros_ci
script:
  - .ros_ci/travis.sh
